ansys/pyansys-cheat-sheet

.github/workflows/ci_cd.yml, README.rst, cheat_sheets/mapdl_cheat_sheet/pymapdl_cheat_sheet.tex, doc/source/index.rst, makefile, static/style.sty
Add the screenshot of the pdf generated adapted from matplotlib. see https://cheatsheets.docs.pyansys.com/
=> Feat: Change the font and create the ss of the pdf

cheat_sheets/pyfluent_cheat_sheet/pyfluent_cheat_sheet.tex
Updated the version for pyfluent cheat sheet.
=> Updated the version for pyfluent cheat sheet

makefile
minor fix on the edb png files
=> FIX: correct the snapshot name for edb api

cheat_sheets/pyprimemesh_cheat_sheet/pyprimemesh_cheat_sheet.log, cheat_sheets/pyprimemesh_cheat_sheet/pyprimemesh_cheat_sheet.tex, doc/source/index.rst, makefile
Cheat sheet for PyPrimeMesh v 0.3.0
=> Feat pyprimemesh cheatsheet

cheat_sheets/general_cheat_sheet_template/pyansys_general_cheat_sheet.tex, cheat_sheets/mapdl_cheat_sheet/pymapdl_cheat_sheet.tex, cheat_sheets/pyfluent_cheat_sheet/pyfluent_cheat_sheet.tex, cheat_sheets/pyprimemesh_cheat_sheet/pyprimemesh_cheat_sheet.tex
@RobPasMue 
Title changed as per recommendation for following cheat sheets
- PyFluent
- PyMAPDL
++@smedikon @agvarghe @MaxJPRey
=> Cheet sheet title changed as per recommendation.

make.bat, makefile
=> FIX: remove pyansys templates from build

make.bat, makefile, static/style.sty
=> fix: errors on build

doc/source/conf.py
=> fix: minor typos and issues with GitHub

doc/source/conf.py, requirements/requirements_doc.txt
=> cicd: update requirements and Sphinx config

static/style.sty
=> FIX: string quotation character

cheat_sheets/pyfluent_cheat_sheet/pyfluent_cheat_sheet.tex
@RobPasMue @Revathyvenugopal162 
Update code snippets using black formatter.
=> Update code snippets using black formatter.

cheat_sheets/pyprimemesh_cheat_sheet/pyprimemesh_cheat_sheet.tex
=> PyPrimeMesh : Fix for Styling according to pep8 styling guidelines

.github/workflows/ci_cd.yml, make.bat, makefile
=> FIX: add the test to check the pdf file

docker/README.md
@RobPasMue 
Updated docker/README.md for Dev environment. Please review.
Thanks!
=> updated readme for Dev environment

cheat_sheets/mapdl_cheat_sheet/pymapdl_cheat_sheet.tex
Couple of english suggestions, a typo, lots of PEP-8 and a change in the GET command cell
=> Fix Style in pyMAPDL cheat sheet

doc/source/index.rst
=> DOC: update layout for 3 column

cheat_sheets/pyensight_cheat_sheet/pyensight_cheat_sheet.tex, cheat_sheets/pyensight_cheat_sheet/pyensight_script.py
Minor changes after discussion with the EnSight team
=> minor changes after team suggestions

cheat_sheets/pydpf-post_cheat_sheet/pydpf-post_cheat_sheet.tex, cheat_sheets/pydpf-post_cheat_sheet/pydpf-post_script.py, doc/source/index.rst, make.bat, makefile
@abhishekchitwar and @Revathyvenugopal162 : Added PyDPF Post Cheatsheet for the review. Please find attached PDF file of cheatsheet.
[pydpf-post_cheat_sheet.pdf](https://github.com/ansys/pyansys-cheat-sheet/files/12333708/pydpf-post_cheat_sheet.pdf)
=> added pydpf post cheatsheet

cheat_sheets/pymechanical_cheat_sheet/pymechanical_script.py
Hi @Revathyvenugopal162 ,
I have updated the command for launching standalone Mechanical : 
https://mechanical.docs.pyansys.com/version/dev/getting_started/running_mechanical.html#launch-mechanical-from-the-command-line
please approve this change
( @klmcadams fyi )
=> pymechanical : updated standalone launch command

cheat_sheets/pymechanical_cheat_sheet/pymechanical_cheat_sheet.tex
Hi @RobPasMue ,
Missed correcting the stable version (0.10)  yesterday. Please approve and merge .
=> pymechanical : added correct stable version

LICENSE, cheat_sheets/pymechanical_cheat_sheet/pymechanical_cheat_sheet.tex, cheat_sheets/pymechanical_cheat_sheet/pymechanical_script.py, doc/source/conf.py
PyMechanical cheat sheet update
=> Update 242 from 232
